version: "3.9"

services:
  app1:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1  # Ensure logs are real-time

  app2:
    build: .
    ports:
      - "8002:8000"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2